---
- name: "1 Play : Menyiapkan Remote Volume"
  hosts: instance_rmv
  remote_user: rmvuser
  gather_facts: no
  vars:
    dir_volume: "/remote_volume"
    mapper: "/dev/mapper"
    pvs: "/dev/sdb"
    vg: "vg_rmv"
    lv: "lv_rmv"
  tasks:
    - name: "1P:T1: Membuat Direktori"
      file:
        state: directory
        path: "{{dir_volume}}"
    - name: "1P:T2: Membuat Dumpfile"
      file:
        state: touch
        path: "{{dir_volume}}/dumpfile"
    - name: "1P:T3: Mengubah Owner"
      ansible.builtin.file:
        path: "{{dir_volume}}"
        owner: rmvuser
        group: rmvuser
        recurse: yes
    - name: "1P:T4.1: Membuat VG"
      community.general.lvg:
        vg: "{{vg}}"
        pvs: "{{pvs}}"
    - name: "1P:T4.2: Membuat LV"
      community.general.lvol:
        vg: "{{vg}}"
        lv: "{{lv}}"
        size: "100%VG"
    - name: "1P:T5: Mengattach Filesytem"
      filesystem:
        fstype: ext4
        dev: "/dev/{{vg}}/{{lv}}"
    - name: "1P:T6: Memounting Device"
      mount:
        path: "{{dir_volume}}"
        src: "{{mapper}}{{vg}}-{{lv}}"
        state: mounted
        fstype: ext4

#####################################################################################

- name: "2 Play : Setup Docker Environment"
  hosts: instance_docker
  remote_user: daemonus
  gather_facts: no
  tasks:
    - name: "2P:T1: Update Package Manager"
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: "2P:T2: Install Docker Dependency"
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: "2P:T3: Add Docker Key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: "2P:T4: Add Docker Repo"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: "2P:T5: Update apt and install docker-ce"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: "2P:T6: Install Docker Modul Python"
      pip:
        name: docker

####################################################################################

- name: "3 Play: Setup Koneksi Instance Docker Ke Instance Remote Volume"
  hosts: instance_docker
  remote_user: daemonus
  vars:
    home_dir: "/home/daemonus"
  gather_facts: no
  tasks:
    - name: "3P:T1: Membuat Keypair"
      openssh_keypair:
        path: "{{home_dir}}/.ssh/id_rsa"
    - name: "3P:T2: Change User dan Group Owner"
      ansible.builtin.file:
        path: "{{home_dir}}/.ssh/id_rsa"
        owner: daemonus
        group: daemonus
    - name: "3P:T3: Menyimpan Public Key Ke Control Node"
      fetch:
        src: "{{home_dir}}/.ssh/id_rsa.pub"
        dest: "tmp/"
        flat: yes
- name: "3 Play : Sub 2"
  hosts: instance_rmv
  remote_user: rmvuser
  vars:
    home_dir: "/home/rmvuser"
  gather_facts: no
  tasks:
    - name: "3P S2 :T1: Meneruskan Public Key Ke Instance Remote Volume"
      copy:
        src: "tmp/id_rsa.pub"
        dest: "/home"
    - name: "3P S2 :T2: Menjadikkan Authorized_Keys"
      shell:      
        cmd: "cat /home/id_rsa.pub >> {{home_dir}}/.ssh/authorized_keys"
####################################################################################

- name: "4 Play: Setup Dependency Docker Volume"
  hosts: instance_docker
  remote_user: daemonus
  vars:
    home_dir: "/home/daemonus"
  gather_facts: no
  tasks:
    - name: "4P:T1: Install Docker Volume Driver"
      shell:
        cmd: "docker plugin install --grant-all-permissions vieux/sshfs"
      ignore_errors: yes
      register: statz
    - name: "4P:T1: Status Install Docker Volume Driver"
      fail:
        msg: "Gagal Menginstall Plugin Vieux/SSHFS"
      failed_when: statz.changed==false
    - name: "4P:T2: Setup SSHKey Source"
      shell:
        cmd: "docker plugin disable vieux/sshfs && docker plugin set vieux/sshfs sshkey.source={{home_dir}}/.ssh/ && docker plugin enable vieux/sshfs"

#####################################################################################

- name: "5 Play: Setup Container APP From DockerCompose"
  hosts: instance_docker
  user: daemonus
  vars: 
    dir_docker_compose: "Project Portofolio #1/Dockerizing Simple Website"
    home_dir: "/home/daemonus"
  gather_facts: no
  tasks:
    - name: "5P:T0: Membuat Direktori Docker"
      file:
        state: directory
        path: "{{home_dir}}/dockerenv"
    - name: "5P:T1: Download Source APP From GitHub"
      ansible.builtin.git:
        repo: https://github.com/ptrsp/CatatanOtodidakKu.git
        dest: "{{home_dir}}/dockerenv"
    - name: "5P:T2: Upgrade Versi PIP"
      pip:
        name: pip
        state: latest
    - name: "5P:T3: Install Package Docker Compose"
      apt:
        name: "docker-compose"
        state: present
    - name: "5P:T4 Install Package Docker Compose Python"
      pip:
        name: docker-compose
    - name: "5P:T5: Create and Start Service"
      community.docker.docker_compose:
        project_src: "{{home_dir}}/dockerenv/{{dir_docker_compose}}"




#    - name: Pull default Docker image
#      community.docker.docker_image:
#        name: "Docker_Image_Name"
#        source: pull
#    - name: Create default containers
#      community.docker.docker_container:
#        name: "Container_Name"
#        image: "Image_name"
#        command: "Optional_Command"
#        state: present
