---
- name: ffirst-playy menginstall dan merestart service {{varG}}
  hosts: iphost
  gather_facts : no
#  vars:
#    servicess:
#      web: firewalld
#      con: httpd
#    varG: firewalld
  vars_files:
    - vars/evars.yml
    - vars/evars2.yml
  tasks:
    - name: task menginstall service {{varG}} dan {{varH}}
      dnf:
        name: "{{item}}"
        state: present
      loop:
        - "{{varG}}"
        - "{{varH}}"
    - name: task merestart service {{varG}}
      service:
        name: "{{varG}}"
        state: started
      register: varDebug
#    - name: print log debug merestart service
#      debug:
#        var: varDebug

#- name: ssecond-playy mengecek ketersediaan file
#  hosts: myhost.example.com
#  become: no
#  tasks:
#    - name: task mengecek ketersediaan file template.txt
#      file:
#        path: /home/anon/template.txt
#        state: file
