---
- name: ffirst-playy menginstall dan mematikan webserver (httpd)
  hosts: iphost
  vars:
    run_my_task: true
    package: httpd
    supported_distros:
      - RedHat
      - fedora
  tasks:
    - name: task menginstall webserver (httpd)
      dnf:
        name: "{{package}}"
        state: present
      when: run_my_task
    - name: task merestart webserver (httpd)
      service:
        name: "{{package}}"
        state: restarted
#      when:
#        - package is defined
#        - ansible_distribution in supported_distros
      when: >
        (ansible_distribution=="RedHat" and ansible_distribution_major_version=="7")
        or
        (ansible_distribution=="Fedora" and ansible_distribution_major_version=="28")
    - name: display log
      debug:
        msg: "{{ansible_distribution}} and {{ansible_distribution_major_version}}"
